version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"

  tester:
    build: .
    depends_on:
      - web
      - redis

    command: ["pytest", "test_app.py"]